### ISSUE TITLE
cordova ios 6.1.0 issue with webview

### ISSUE THREAD

**Issue by 21pg** [apache/cordova-ios#1044] opened 2020-12-15 14:02 UTC
# Bug Report
I am trying to  upgrade my app from cordova -ios 5.1.1 to cordova-ios 6.1.0
My app running good on cordova-ios 5.1.1
For cordova-ios 6.1.0 I am doing following changes-

- cordova platform add ios@6.1.0
-  I removed cordova-plugin-ionic-webview ( If not , it throws build error)
 `  cordova plugin rm cordova-plugin-ionic-webview`
- I removed following from config.xml -
```
<preference name="WKWebViewOnly" value="true" />
<feature name="CDVWKWebViewEngine">
    <param name="ios-package" value="CDVWKWebViewEngine" />
</feature>
```
Now i added -
```
cordova plugin add @globules-io/cordova-plugin-ios-xhr
  <preference name="AllowUntrustedCerts"  value="true" />
  <preference name="InterceptRemoteRequests" value="all" />
  <preference name="allowFileAccessFromFileURLs" value="true" />
  <preference name="allowUniversalAccessFromFileURLs" value="true" />
```
- upgraded cordova-plugin-splashscreen@6.0.0
## Problem
My app works fine on cordova ioa 5.1.1 but after this changes for 6.1.0,
I am getting unsafe area below to notch in iPhone XR and 
iPhone X.
![IMG_20201212_140731](https://user-images.githubusercontent.com/64975861/102223527-d6267700-3f0a-11eb-8a24-50b87e6f4396.jpg)

### What is expected to happen?
it should load normally
![Skype_Picture](https://user-images.githubusercontent.com/64975861/102223912-4d5c0b00-3f0b-11eb-9897-05bbf8957bfe.jpeg)

## Information
I using framework 7 with vue js

### Command or Code

`<?xml version="1.0" encoding="UTF-8"?>
<widget xmlns="http://www.w3.org/ns/widgets" xmlns:gap="http://phonegap.com/ns/1.0" id="" version="22.7.1">
   <name>Live</name>
   <description></description>
   <preference name="orientation" value="portrait" />
   <preference name="deployment-target" value="11.0" />
   <preference name="prerendered-icon" value="false" />
   <preference name="DisallowOverscroll" value="true" />
   <preference name="SplashScreenDelay" value="3000" />
   <preference name="AllowInlineMediaPlayback" value="true" />
   <preference name="mediaTypesRequiringUserActionForPlayback" value="none" />
   <preference name="detect-data-types" value="false" />
   <preference name="HideKeyboardFormAccessoryBar" value="true" />
   <preference name="permissions" value="INTERNET" />
   <preference name="AllowUntrustedCerts"  value="true" />
  <preference name="InterceptRemoteRequests" value="all" />
  <preference name="allowFileAccessFromFileURLs" value="true" />
  <preference name="allowUniversalAccessFromFileURLs" value="true" />
<feature name="http://api.phonegap.com/1.0/file" />
   <feature name="NetworkStatus">
      <param name="ios-package" value="org.apache.cordova.networkinformation.NetworkManager" />
   </feature>
   <feature name="SocialSharing">
      <param name="ios-package" value="cordova-plugin-x-socialsharing" />
   </feature>
   <feature name="Notification">
      <param name="ios-package" value="org.apache.cordova.dialogs.Notification" />
   </feature>
   <feature name="PushPlugin">
      <param name="ios-package" value="com.plugin.gcm.PushPlugin" />
   </feature>
   <plugin name="phonegap-plugin-push" spec="2.3.0" source="npm">
      <param name="SENDER_ID" value="xxxxxx" />
   </plugin>
   <platform name="ios">
      <config-file target="* -Info.plist" parent="UIBackgroundModes" overwrite="true"><array><string>audio</string></array></config-file>
      <splash height="480" platform="ios" src="res/screen/ios/Default.png" width="320" />
      <splash height="960" platform="ios" src="res/screen/ios/Default@2x.png" width="640" />
      <splash height="1136" platform="ios" src="res/screen/ios/Default-568h@2x.png" width="640" />
      <splash src="res/screen/ios/Default@2x~iphone~anyany.png" />
      <splash src="res/screen/ios/Default@2x~iphone~comany.png" />
      <splash src="res/screen/ios/Default@2x~iphone~comcom.png" />
      <splash src="res/screen/ios/Default@3x~iphone~anyany.png" />
      <splash src="res/screen/ios/Default@3x~iphone~anycom.png" />
      <splash src="res/screen/ios/Default@3x~iphone~comany.png" />
      <splash src="res/screen/ios/Default@2x~ipad~anyany.png" />
      <splash src="res/screen/ios/Default@2x~ipad~comany.png" />
   </platform>
   <access origin="*" subdomains="true" />
   <allow-intent href="http://*/*" />
   <allow-intent href="https://*/*" />
   <allow-intent href="tel:*" />
   <allow-intent href="sms:*" />
   <allow-intent href="mailto:*" />
   <allow-intent href="geo:*" />
   <allow-navigation href="https://www.youtube.com/*" />
   <allow-navigation href="http://www.youtube.com/*" />
   <allow-navigation href="https://player.vimeo.com/*" />
   <allow-navigation href="http://player.vimeo.com/*" />
   <plugin name="cordova-plugin-keyboard" spec="~1.2.0" />
   <plugin name="cordova-plugin-device" spec="~2.0.3" />
   <plugin name="cordova-plugin-network-information" spec="~2.0.1" />
   <plugin name="cordova-plugin-media" spec="~5.0.3">
      <variable name="KEEP_AVAUDIOSESSION_ALWAYS_ACTIVE" value="NO" />
   </plugin>
   <plugin name='cordova-plugin-background-mode' source='npm' spec='0.7.3'/>
   <plugin name="cordova-plugin-theme-detection" spec="~1.2.0" />
   <plugin name="cordova-plugin-whitelist" spec="~1.3.3" />
   <plugin name="cordova-plugin-x-socialsharing" spec="~5.3.1" />
   <plugin name="cordova-sqlite-evcore-extbuild-free" spec="~0.9.2" />
</widget>`

### Environment, Platform, Device
Iphone X , Iphone XR

### Version information
cordova 10.0.0
cordpva -ios 6.1.0
xcode 12

## Checklist

- [Y ] I searched for existing GitHub issues
- [Y ] I updated all Cordova tooling to most recent version
- [Y ] I included all the necessary information above

**Comment by timbru31** [comment] 2020-12-15 14:15
Closing as a duplicate of https://github.com/apache/cordova-plugin-splashscreen/issues/305 - one issue is enough.

**Comment by timbru31** [comment] 2020-12-15 16:44
Closing as OP found a solution (https://github.com/apache/cordova-ios/issues/933#issuecomment-722241225)

**Closed by timbru31** 2020-12-15 16:44 UTC
