### ISSUE TITLE
API calls failed on IPhone XR

### ISSUE THREAD

**Issue by rijink7** [apache/cordova-ios#618] opened 2019-05-16 04:05 UTC
# Bug Report

## Problem
There is no error with the build. it works fine in IPhone 6 & 7 which works on IOS 12.2 and unable to access API's from iPhone Xr when its on cellular network(Sprint LTE ) and the API's works when its connected through WIFI Network.  

### Version information

Ionic:

   ionic (Ionic CLI)  : 4.1.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.5
   @ionic/app-scripts : 3.1.8

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 2 5.0.0, ios 5.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.0.5, cordova-plugin-ionic-webview 2.3.1, (and 20 other plugins)

System:

   Android SDK Tools : 26.0.2 (/Users/afscdev/Library/Android/sdk)
   ios-deploy        : 1.9.2
   ios-sim           : 7.0.0
   NodeJS            : v11.8.0 (/usr/local/bin/node)
   npm               : 6.5.0
   OS                : macOS
   Xcode             : Xcode 10.2.1 Build version 10E1001

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by jcesarmobile** [comment] 2019-06-11 12:02
This is a configuration problem in your network/server or some restriction in your celular provider.

**Comment by vyacheslav-lonschakov** [comment] 2019-06-14 04:59
We had the same issue on iPhone X. Was fixed by reverting back to cordova-ios@4.5.2.

**Comment by janpio** [comment] 2019-06-14 05:55
Is this reproducible in a new, plain Cordova app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by jcesarmobile** [comment] 2019-06-27 14:59
I've tried once again with cordova-ios 5.0.1 and I can't reproduce, so I'm going to close the issue.

**Closed by jcesarmobile** 2019-06-27 14:59 UTC
Labels: support
