### ISSUE TITLE
WDA is not working for appium test on VM's with cordova 5.1.1

### ISSUE THREAD

**Issue by Ichhakhemka** [apache/cordova-ios#767] opened 2020-01-18 02:54 UTC
Regression was working perfectly fine for app with older version of cordova but now
WebDriverAgent is not launching for appium test on VM's with cordova 5.1.1. Please help.

Environment, Platform, Device:
iOS
simulator : iPhone 7 -12.1

Version information:
cordova-ios 5.1.1
Appium: v1.16.1
xocde: 11.0
Macos:  10.14.6

**Comment by timbru31** [comment] 2020-01-24 23:48
Thanks a lot for your issue, however the issue template exists for a reason. 😊.  
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.

Besides that, is this reproducible in a new, plain Cordova app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by brodybits** [comment] 2020-02-18 19:55
Closing due to lack of requested information. Please feel free to raise a *new* issue with a [minimal, reproducible example ([1])](https://stackoverflow.com/help/minimal-reproducible-example). It should reproducible for us in a new, plain Cordova app, with the other information requested by the issue template.

[1] https://stackoverflow.com/help/minimal-reproducible-example

**Closed by brodybits** 2020-02-18 19:55 UTC
