### ISSUE TITLE
build.json not working with 5.0.0

### ISSUE THREAD

**Issue by oslr** [apache/cordova-ios#625] opened 2019-06-01 14:08 UTC
I have a cordova app (built using corber.io) that I compile using the command line with this command:

`corber build --platform ios --environment cordova --release --build-config "corber/cordova/build.json"`

This loads signing identities and provisioning profiles from build.json, which looks like this:

```
{
  "ios": {
    "release": {
      "codeSignIdentity": "XXXX",
      "provisioningProfile": "XXXX",
      "developmentTeam": "XXXX",
      "packageType": "app-store",
      "buildFlag": [
        "-UseModernBuildSystem=0"
      ]
    }
  }
}
```

This works fine in cordova-ios@4.5.5 but after upgrading to cordova-ios@5.0.0 it does not seem to read the code signing identity or provisioning profile any more - I get the following warning:

`xcode project is configured for manual signing, but no provisioning profile has been selected; project may build, but archive will fail.`

and the build fails with the error:

```
Corber: xcodebuild: Command failed with exit code 65
WARNING: corber 
No signing identity has been configured for your xcode project. If you have received an "ARCHIVE FAILED" message with error code 65, you will need to run "corber open ios" and set your development team (for automatic signing), or set your release provisioning profile (for manual signing).
```

This problem does seem to be specific to cordova-ios as it resolves after running `corber platform remove ios` then `corber platform add ios@4.5.5`. Do I need to update my build settings for the new release? 

Many thanks

**Comment by Tallyb** [comment] 2019-06-05 09:58
remove 
```
"buildFlag": [
        "-UseModernBuildSystem=0"
      ]
```
Cordova-ios 5 is using the modern build system introduced in xcode 10.1

**Comment by oslr** [comment] 2019-06-05 13:02
Thanks - but this didn't fix it unfortunately. The build still does not seem to register the code signing identity or provisioning profile defined in build.json as it did in 4.5.5.

**Comment by janpio** [comment] 2019-06-05 13:27
Does it work outside the context of corber, just with plain `cordova` commands?

**Comment by oslr** [comment] 2019-06-06 19:56
No. I tried:

```
cd corber/cordova
cordova build ios --release --buildConfig=./build.json
```

But it still doesn't seem to pick up the code signing certificate. I have managed to get it working by manually specifying build flags as below. Again, this is 5.0.x specific - has the method of parsing these variables from build.json changed?

```
{
  "ios": {
    "release": {
      "codeSignIdentity": "XXXX",
      "provisioningProfile": "XXXX",
      "developmentTeam": "XXXX",
      "packageType": "app-store",
      "buildFlag": [
        "DEVELOPMENT_TEAM=XXXX",
        "CODE_SIGN_IDENTITY=XXXX",
        "PROVISIONING_PROFILE_SPECIFIER=XXXX",
        "CODE_SIGN_ENTITLEMENTS=XXXX/Entitlements-Release.plist"
      ]
    }
  }
}
```

**Comment by davidachin** [comment] 2019-06-21 19:15
I had the same issue, but was able to fix by switching to use the UUID on the provisioningProfile property:

`"provisioningProfile": "My ProPro Distro"` to `"provisioningProfile": "123-456"`

**Comment by dpogue** [comment] 2023-04-16 00:45
Closing as duplicate of #536

**Closed by dpogue** 2023-04-16 00:45 UTC
