### ISSUE TITLE
Podfile multiple targets generated if single quote is used in app name

### ISSUE THREAD

**Issue by mikealo** [apache/cordova-ios#717] opened 2019-11-11 15:57 UTC
# Bug Report
Podfile multiple targets generated if single quote is used in app name, this issue is not created if app does not contain single quote

## Problem
If a single quote is used in the app name for example "Test's single quote" and there is any additional plugin that use any pod library then the podfile generated contains multiple targets and cordova fail the plugin installation

### What is expected to happen?
The podfile generated should look like this:

```
platform :ios, '9.0'
target 'Test\'s single quote' do
	project 'Test\'s single quote.xcodeproj'
	pod 'GoogleMaps', '~> 2.0.0'
end

```
### What does actually happen?
The podfile generated look like this:

```
platform :ios, '9.0'
target 'Test\'s single quote' do
	project 'Test\'s single quote.xcodeproj'
end
target 'Test\'s single quote' do
	project 'Test\'s single quote.xcodeproj'
	pod 'GoogleMaps', '~> 2.0.0'
end
```

### Command or Code
```
cordova create "Test's single quote" com.test.singlequote "Test's single quote"
cordova platform add ios
cordova plugin add cordova-plugin-googlemaps

```

### Version information
MacOS 10.15
Xcode 11.2
Node v12.5.0
Ruby Gem 3.0.6
CocoaPods 1.8.4
Cordova 9.0.0 (cordova-lib@9.0.1)
Cordova iOS platform 5.0.1

## Checklist
- [X] I searched for existing GitHub issues
- [X] I updated all Cordova tooling to most recent version
- [X] I included all the necessary information above

**Comment by mibzman** [comment] 2019-12-17 19:47
I'm having this issue as well.  @mikealo, did you discover a workaround?

**Comment by mikealo** [comment] 2019-12-18 12:40
@mibzman unfortunatly i ended app changing app name and removing single quote.

Even if you change the podfile generated in the project>platform>ios folder manually you can then create errors during build process so i avoided doing so.

The file on ios platform that generate the podfile should be this one:

https://github.com/apache/cordova-ios/blob/master/bin/templates/scripts/cordova/lib/Podfile.js 

But even if change it manually this can lead to other errors so i think this is something that should be easily corrected by who works on it.

**Comment by mibzman** [comment] 2019-12-18 18:49
Thanks for the response.  I've also ended up changing my app name.  I removed the single quote from the  `name` property and went with a combination of [this plugin](https://github.com/mibzman/cordova-plugin-app-name) and [this config](https://stackoverflow.com/a/47583130/2653503) to change the display name back to a name with the single quote.

Hopefully, the core team can get to fixing this soon.

**Comment by RobWouters** [comment] 2021-07-29 10:01
I have not confirmed this but I suspect the problem is with this regex here:
https://github.com/apache/cordova-ios/blob/a3a3936a549981054dabff8098dfa393094eb834/bin/templates/scripts/cordova/lib/Podfile.js#L81

**Comment by RobWouters** [comment] 2021-07-29 10:27
I have not confirmed this but I suspect the culprit is this regex:
https://github.com/apache/cordova-ios/blob/a3a3936a549981054dabff8098dfa393094eb834/bin/templates/scripts/cordova/lib/Podfile.js#L81

**Comment by csi-slizhevskyv** [comment] 2023-11-27 12:05
the same issue. UP!

**Comment by dpogue** [comment] 2024-09-26 08:38
Just noting that even if this Podfile issue is resolved in Cordova (which it hopefully will be soon), there are other issues in Cocoapods regarding project names with single quotes: https://github.com/CocoaPods/CocoaPods/issues/7546

**Closed** 2024-10-08 07:02 UTC
Labels: help wanted
