### ISSUE TITLE
IOS 12.2 beta2 webview functions with animations not working 

### ISSUE THREAD

**Issue by karthibv** [apache/cordova-ios#537] opened 2019-02-19 10:56 UTC
Currently my application, some angular animation in UIWebview in background is not working.
Following stuff i'm doing in current app,

Creating a cordovaviewcontroller instance in background and supplying start page link. And just have this instance in property and not rendering this view controller in screen.

Few angular resource are loaded in background itself in the cordova instance which i created in step 1, to improve the webview loading performance.

Durning some button action, I'm opening Viewcontroller with cordovaviewcontroller view as subview and rending specific angular screen with animation.

Everything working fine <12.2 beta.

In 12.2 beta, some of the angular animation are not working properly.

We tried to remove the angular animation and tried. After that, angular screen rendering properly without animation.

One more step also I tried, instead of initializing cordova in background, created cordova instance in foreground and rendered viewcontroller, now also everything working fine.

Is loading web stuff in background, causing issue? I really need that background loading part for the performance.

Any help is appreciated.

STEPS TO REPRODUCE
1) Create a Cordova application
2) On Launch - foreground have simple native page with link to open webview
3) On Launch - background to load the sample angular page with transform: 'translate3d animation. have some links in angular page and do the translate3d animation to load the other pages
4) < io12.2 beta - its working fine. issue is happening in ios 12.2 beta. After sample app launch and then click of webview link .. links takes to webview page but nothing working there.,

Version information
Cordova-IOS - v4.3
IOS 12.2 beta2

**Comment by janpio** [comment] 2019-02-19 14:44
Do you have a proper Cordova app here or a native app that uses the Cordova webview? How do you build your app?

> Cordova-IOS - v4.3

Your Cordova tooling seems to be out of date, which might be causing all kinds of problems. 
You can read about how to figure out the current Cordova versions and how to update CLI, platforms and plugins here: https://ionic.zone/cordova/update

**Comment by karthibv** [comment] 2019-02-20 07:40
We tried upgrading latest cordova version also and still same issue. is there any issue due to web-animation partial supported provided as part of IOS 12.2 ?. Our app use extensive Angular animation with poly fill.

**Comment by janpio** [comment] 2019-03-01 13:46
Is this reproducible in a new, plain Cordova app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by karthibv** [comment] 2019-03-31 02:24
Issue not there from 12.2 beta4 onwards. l have raised as bug to apple and it seems solved by apple in beta4 ,5,6. now final version does not have the issue.

**Comment by jcesarmobile** [comment] 2019-06-14 08:14
Closing as it was an apple issue

**Closed by jcesarmobile** 2019-06-14 08:14 UTC
Labels: iOS 12, support
