### ISSUE TITLE
[Error] Cross-origin redirection to http://developers.google.com/ denied by Cross-Origin Resource Sharing policy: Origin ionic://localhost is not allowed by Access-Control-Allow-Origin. Status code: 301

### ISSUE THREAD

**Issue by balaji-nilaapps** [apache/cordova-ios#1318] opened 2023-04-24 10:50 UTC
# Bug Report

## Problem
 Cross-origin redirection to http://developers.google.com/ denied by Cross-Origin Resource Sharing policy: Origin ionic://localhost is not allowed by Access-Control-Allow-Origin. 
### What is expected to happen?
Show popup for select account for sign-in with google or facebook or apple using firebase 

### What does actually happen?

Show  Cross-origin redirection to http://developers.google.com/ denied by Cross-Origin Resource Sharing policy: Origin ionic://localhost is not allowed by Access-Control-Allow-Origin. 

### Version information
@angular/*:^15.2.5
@ionic/angular:^6.7.0
cordova-ios:6.3.0
firebase:^9.20.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by dpogue** [comment] 2023-04-24 13:18
FYI if you're trying to do OAuth for login, [Google won't let you do that in the Cordova WebView](https://developers.googleblog.com/2021/06/upcoming-security-changes-to-googles-oauth-2.0-authorization-endpoint.html) anymore because of security concerns.

You might need to look at options for compliant OAuth support, such as [what Firebase recommends](https://firebase.google.com/docs/auth/web/cordova) or [cordova-plugin-oauth](https://www.npmjs.com/package/cordova-plugin-oauth).

**Comment by breautek** [comment] 2023-04-24 21:28
> firebase:^9.20.0

This is the Web JS API, which is [explicitly](https://firebase.google.com/docs/web/environments-js-sdk#auth-note) mentioned to be not supported in Cordova Environments.

See their Athentication module note:

> Note: All Authentication features, except phone authentication and popup/redirect OAuth operations, are supported.

Therefore popup authentication is only supported in a real browser and not inside an embedded webview.

dpogue's [comment](https://github.com/apache/cordova-ios/issues/1318#issuecomment-1520146884) has links for the why Google/Firebase does not support Cordova/embedded webviews in this manner as well as links for what to do instead.

Closing as not a bug / won't fix.

**Closed by breautek** 2023-04-24 21:28 UTC

**Comment by sdeprada** [comment] 2025-05-06 07:55
In my case, I was getting that error on IOS too, in the Safari Web Inspector Console, but this wasn't the first error. Before this, the next error was shown:
[Error] TypeError: undefined is not an object (evaluating 'gapi.iframes.getContext')
and later, the Cross-Origin error described in the title.
The root cause was the firebase initialization. For IOS, you have to initialize de Firebase Auth module specifying the persistence, so you have to use this:

`const app = initializeApp(environment.firebase);
initializeAuth(app, {
    persistence: indexedDBLocalPersistence
});`

instead of this:

`
const app = initializeApp(environment.firebase);
const auth = getAuth(app);`
