### ISSUE TITLE
Unable to distribute with Xcode 10

### ISSUE THREAD

**Issue by neofuture** [apache/cordova-ios#412] opened 2018-09-18 13:30 UTC
When trying to push a project to app store with Xcode 10 i get the following new error

ERROR ITMS-90174: "Missing Provisioning Profile - Apps must contain a provisioning profile in a file named embedded.mobileprovision."

**Comment by janpio** [comment] 2018-09-18 13:34
Push how?
Who exactly outputs that error when?
How did you build the project? (Do you have the complete build output?)
Did this exact project work before upgrading to Xcode 10?

**Comment by neofuture** [comment] 2018-09-18 13:37
Project was opened in Xcode 10, built then Distributed from the Xcode10 organiser, the project worked fine with Xcode 9 without any changes. i dont have build output as i have to use Xcode to build

**Comment by janpio** [comment] 2018-09-18 13:50
Right now we only have workaround for builds with the CLI published over at https://github.com/apache/cordova-ios/issues/407. You might need some instructions on how to get a Xcode only project to work. Someone will have to look into this.

**Comment by neofuture** [comment] 2018-09-18 13:58
Yes, i have just built with CLI and it built and ran in simulator but i need to distribute to the app store and cant without Xcode, so cant put anything onto test flight.

**Comment by neofuture** [comment] 2018-09-18 14:07
I was going to try and use the CLI and create the app store package and use application loader ive tried 

cordova build ios --buildFlag="-UseModernBuildSystem=0" --packageType="app-store"

but i only get the normal .app file in the emulator folder which application loader will not deal with

**Comment by dpogue** [comment] 2018-09-18 14:09
Try `cordova build ios --release --device --buildFlag="-UseModernBuildSystem=0" --packageType="app-store"`

**Comment by sufian4199** [comment] 2018-09-18 14:10
Facing the same issue. 

ionic cordova build ios --buildFlag="-UseModernBuildSystem=0" allows you to make the build. However not able to submit it to the store. It gives the same error as @neofuture mentioned

**Comment by sufian4199** [comment] 2018-09-18 14:13
> cordova build ios --release --device
Discovered plugin "call-number" in config.xml. Adding it to the project
Plugin "mx.ferreyra.callnumber" already installed on android.
Plugin "mx.ferreyra.callnumber" already installed on ios.
Building project: /Users/muhammadsufian/Documents/GITREPOS/driveit/userApp/platforms/ios/DriveIt.xcworkspace
	Configuration: Release
	Platform: device
User defaults from command line:
    IDEArchivePathOverride = /Users/muhammadsufian/Documents/GITREPOS/driveit/userApp/platforms/ios/DriveIt.xcarchive

Build settings from command line:
    CONFIGURATION_BUILD_DIR = /Users/muhammadsufian/Documents/GITREPOS/driveit/userApp/platforms/ios/build/device
    SHARED_PRECOMPS_DIR = /Users/muhammadsufian/Documents/GITREPOS/driveit/userApp/platforms/ios/build/sharedpch

Build settings from configuration file '/Users/muhammadsufian/Documents/GITREPOS/driveit/userApp/platforms/ios/cordova/build-release.xcconfig':
    CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES = YES
    CODE_SIGN_ENTITLEMENTS = $(PROJECT_DIR)/$(PROJECT_NAME)/Entitlements-$(CONFIGURATION).plist
    CODE_SIGN_IDENTITY = iPhone Distribution
    ENABLE_BITCODE = NO
    FRAMEWORK_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/FirebaseAnalytics/Frameworks" "${PODS_ROOT}/FirebaseCore/Frameworks" "${PODS_ROOT}/FirebaseInstanceID/Frameworks" "${PODS_ROOT}/FirebaseMessaging/Frameworks"
    GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1 $(inherited) GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS=1 $(inherited) PB_FIELD_32BIT=1 PB_NO_PACKED_STRUCTS=1
    HEADER_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/Headers/Public" "${PODS_ROOT}/Headers/Public/FirebaseAnalytics" "${PODS_ROOT}/Headers/Public/FirebaseCore" "${PODS_ROOT}/Headers/Public/FirebaseInstanceID" "${PODS_ROOT}/Headers/Public/FirebaseMessaging" "${PODS_ROOT}/Headers/Public/GoogleToolboxForMac" "${PODS_ROOT}/Headers/Public/Protobuf" "${PODS_ROOT}/Headers/Public/nanopb"
    LIBRARY_SEARCH_PATHS = $(inherited) "${PODS_CONFIGURATION_BUILD_DIR}/GoogleToolboxForMac" "${PODS_CONFIGURATION_BUILD_DIR}/Protobuf" "${PODS_CONFIGURATION_BUILD_DIR}/nanopb"
    OTHER_CFLAGS = $(inherited) -isystem "${PODS_ROOT}/Headers/Public" -isystem "${PODS_ROOT}/Headers/Public/FirebaseAnalytics" -isystem "${PODS_ROOT}/Headers/Public/FirebaseCore" -isystem "${PODS_ROOT}/Headers/Public/FirebaseInstanceID" -isystem "${PODS_ROOT}/Headers/Public/FirebaseMessaging" -isystem "${PODS_ROOT}/Headers/Public/GoogleToolboxForMac" -isystem "${PODS_ROOT}/Headers/Public/Protobuf" -isystem "${PODS_ROOT}/Headers/Public/nanopb"
    OTHER_LDFLAGS = $(inherited) -ObjC -l"GoogleToolboxForMac" -l"Protobuf" -l"c++" -l"nanopb" -l"sqlite3" -l"z" -framework "AddressBook" -framework "FirebaseAnalytics" -framework "FirebaseCore" -framework "FirebaseCoreDiagnostics" -framework "FirebaseInstanceID" -framework "FirebaseMessaging" -framework "FirebaseNanoPB" -framework "StoreKit" -framework "SystemConfiguration"
    PODS_BUILD_DIR = ${BUILD_DIR}
    PODS_CONFIGURATION_BUILD_DIR = ${PODS_BUILD_DIR}/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
    PODS_PODFILE_DIR_PATH = ${SRCROOT}/.
    PODS_ROOT = ${SRCROOT}/Pods
    SWIFT_OBJC_BRIDGING_HEADER = $(PROJECT_DIR)/$(PROJECT_NAME)/Bridging-Header.h

error: archive not found at path '/Users/muhammadsufian/Documents/GITREPOS/driveit/userApp/platforms/ios/DriveIt.xcarchive'
** EXPORT FAILED **

(node:17836) UnhandledPromiseRejectionWarning: Error code 65 for command: xcodebuild with args: -exportArchive,-archivePath,DriveIt.xcarchive,-exportOptionsPlist,/Users/muhammadsufian/Documents/GITREPOS/driveit/userApp/platforms/ios/exportOptions.plist,-exportPath,/Users/muhammadsufian/Documents/GITREPOS/driveit/userApp/platforms/ios/build/device
(node:17836) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17836) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

@dpogue even this does not solve the signing issue

**Comment by neofuture** [comment] 2018-09-18 14:18
That created the IPA fine, but... application loader can not connect to the app store anymore so thats that one scuppered, i can see a lot of frustration from todays Xcode 10 auto update as no one will now be able to publish there app

**Comment by neofuture** [comment] 2018-09-18 14:55
Temporary Fix: I went back to Xcode 9.4.1 from he developer downloads at developer.apple.com, reopened the project with this and was able to upload to the app store.

For notice: I was previously building the project with Xcode Beta (i like the black theme) and was using Xcode 9 for uploading to app store. i have no problems building in Xcode 10 my only issue is distribution to the app store.

**Comment by mlegenhausen** [comment] 2018-09-18 15:04
I used `fastlane deliver` today for uploading two apps build with Xcode 10 without problems. The only thing that needed to be changed so the signing was working was to change the `ProvisioningStyle` to `Manual` in all `project.pbxproj` files. Then you can set your `codeSignIdentity` and `provisioningProfile` via your `build.json`.

```js
sh.sed(
    '-i',
    /ProvisioningStyle = Automatic/,
    'ProvisioningStyle = Manual',
    'platforms/ios/**/project.pbxproj'
  );
```

**Comment by sufian4199** [comment] 2018-09-18 15:33
@neofuture i was able to submit app via xcode but now instead of wildcard i had to create an individual provisioning profile for each app. However after that everything worked as expected.

**Comment by pliablepixels** [comment] 2018-09-18 15:41
@sufian4199 how did you submit app? Are you still using Xcode 10? I am able to build with `ionic cordova build ios -- --buildFlag="-UseModernBuildSystem=0"` but when I archive via Xcode 10 and try to validate it, I am stuck with the missing mobile provision error.

**Comment by sufian4199** [comment] 2018-09-18 15:49
Yes i am submitting via xcode 10. I did the following things

1) Created provisioning profile in my developer account for that app id. 
2) Downloaded and added that profile in my Xcode (simply double click the downloaded profile)
3) Instead of auto signing the code i used manual and used that specific provisioning profile and all went well

PS: I however dont know why this happened because auto signing was working perfectly for me on xcode 9. However doing this gets the job done 👍

**Comment by kitolog** [comment] 2018-09-18 15:58
I got the same issue using Xcode 10
I cannot also distribute the latest build via Fabric or run ios app using cli
Xcode 10
iOS 12
macOS 10.13.6
Ionic 3.20.0
Cordova 8.0.0
cordova-ios 4.5.5

**Comment by pliablepixels** [comment] 2018-09-18 15:59
@sufian4199 - I can confirm your solution works. To summarize the hacks so far:

1. While building, we need to do (if using ionic) `ionic cordova build ios -- --buildFlag="-UseModernBuildSystem=0"`
2. When you open it in Xcode, you can continue using "Automatic Sign" for the project, but when you upload the archive to App Store (for TestFlight or App Store) 

I've currently loaded  - will edit this message after I know for sure it works and I can test it via test flight

**Comment by sufian4199** [comment] 2018-09-18 16:06
@pliablepixels thank you for summarising it in the best possible way 👍

**Comment by dpogue** [comment] 2018-09-18 16:33
@pliablepixels @mlegenhausen Thanks for providing more information to help us understand what's going on! I might be missing something, but it seems like it's unclear whether this is an Xcode issue with automatic signing, or a Cordova issue with how we set up the automatic signing.

Could you help fill in this table?

| | Export with<br>Automatic Signing | Export with<br>Manual Signing |
|-|-|-|
| Xcode IDE | | |
| Cordova/Ionic CLI | | |
| *Bonus Info:*<br>Fastlane CLI | | |

<details><summary>Table Markup for copy/paste</summary>

```
|                               | Export with<br>Automatic Signing | Export with<br>Manual Signing |
|-------------------------------|----------------------------------|-------------------------------|
| Xcode IDE                     |                                  |                               |
| Cordova/Ionic CLI             |                                  |                               |
| *Bonus Info:*<br>Fastlane CLI |                                  |                               |
```
</details>

**Comment by rossholdway** [comment] 2018-09-18 17:31
From my testing... others should probably confirm :)

|                               | Export with<br>Automatic Signing | Export with<br>Manual Signing |
|-------------------------------|----------------------------------|-------------------------------|
| Xcode IDE   |  Export will succeed, but won't validate due to missing profile (embedded.mobileprovision)    |  Export will succeed, validation will succeed             |
| Cordova/Ionic CLI             |  Works, but **only** if run with `UseModernBuildSystem=0` (this also seems to trigger the initial generation of the Xcode managed profiles).                             |     Works, manually specifying the distribution profile.                         |
| *Bonus Info:*<br>Fastlane CLI |                                  |

**Comment by dpogue** [comment] 2018-09-18 17:54
hmm, that confuses me a bit because everyone seems to be saying that Cordova with automatic signing is resulting in the error about missing embedded.mobileprovision.

**Comment by pliablepixels** [comment] 2018-09-18 18:33
@rossholdway for the Xcode IDE row when you say "validation will succeed" what exactly are you doing? I tried exporting both automatic and manual - they both exported. But both of them refused to get installed back saying "valid provisional profile not found" which is completely weird because the manual signing version went through to the store. Its possible I'm messing up somewhere, so I plan to revisit this tomorrow if the problem hasn't already been diced and sorted.

**Comment by dpogue** [comment] 2018-09-18 21:48
@pliablepixels I assume that `ad-hoc` or `app-store` (or even `enterprise`) would be fine... It has to sign the build in all cases.

Maybe I'm confused about this issue... is there a problem wherein Cordova CLI is making builds with missing embedded mobileprovision files, or is the issue that Xcode makes builds with missing profiles when exporting Cordova projects? I guess we need more information from @neofuture about which export process was being used

**Comment by pliablepixels** [comment] 2018-09-18 21:55
I'm completely confused as well, so I'll retract and wait for others more qualified than me to report, so as not to confuse you. In the morning, a simple `ionic cordova build ios` would fail but now, in the evening I see the same error message, but it continues to build and export. I don't quite follow the CLI process well, so I think its best we wait for folks who know what they are doing :-)

In the morning:
```
{PODS_ROOT}/Headers/Public/FirebaseCore" -isystem "${PODS_ROOT}/Headers/Public/FirebaseInstanceID" -isystem "${PODS_ROOT}/Headers/Public/FirebaseMessaging" -isystem "${PODS_ROOT}/Headers/Public/GoogleToolboxForMac" -isystem "${PODS_ROOT}/Headers/Public/Protobuf" -isystem "${PODS_ROOT}/Headers/Public/nanopb"
    OTHER_LDFLAGS = $(inherited) -ObjC -l"GoogleToolboxForMac" -l"Protobuf" -l"c++" -l"nanopb" -l"sqlite3" -l"z" -framework "AddressBook" -framework "FirebaseAnalytics" -framework "FirebaseCore" -framework "FirebaseCoreDiagnostics" -framework "FirebaseInstanceID" -framework "FirebaseMessaging" -framework "FirebaseNanoPB" -framework "StoreKit" -framework "SystemConfiguration"
    PODS_BUILD_DIR = $BUILD_DIR
    PODS_CONFIGURATION_BUILD_DIR = $PODS_BUILD_DIR/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
    PODS_PODFILE_DIR_PATH = ${SRCROOT}/.
    PODS_ROOT = ${SRCROOT}/Pods
    SWIFT_OBJC_BRIDGING_HEADER = $(PROJECT_DIR)/$(PROJECT_NAME)/Bridging-Header.h

2018-09-18 17:51:25.569 xcodebuild[60657:1388992]  DTDeviceKit: deviceType from 8a7f8ff88e79aca165c1f88cc6770c3447630a03 was NULL
2018-09-18 17:51:25.569 xcodebuild[60657:1388992]  DTDeviceKit: deviceType from 8a7f8ff88e79aca165c1f88cc6770c3447630a03 was NULL
2018-09-18 17:51:25.570 xcodebuild[60657:1388992]  iPhoneSupport: 📱<DVTiOSDevice (0x7f96c8d034b0), PP iPhone X, iPhone, 12.0 (16A366), 83f9f3a76dac77d2afe8a2acc9a14a8ec96d1f34> unable to mount DeveloperDiskImage (Error Domain=com.apple.dtdevicekit Code=601 "Could not findplatform" UserInfo={NSLocalizedDescription=Could not find platform})
```
It would fail around here

But now, it prints the above message and continues on to:

```
2018-09-18 17:51:26.268 xcodebuild[60657:1388881] [MT] DTDeviceKit: deviceType from 8a7f8ff88e79aca165c1f88cc6770c3447630a03 was NULL
2018-09-18 17:51:26.297 xcodebuild[60657:1388881] [MT] DTDeviceKit: deviceType from 8a7f8ff88e79aca165c1f88cc6770c3447630a03 was NULL
2018-09-18 17:51:26.353 xcodebuild[60657:1388881] [MT] DTDeviceKit: deviceType from 8a7f8ff88e79aca165c1f88cc6770c3447630a03 was NULL
2018-09-18 17:51:26.386 xcodebuild[60657:1388881] [MT] DTDeviceKit: deviceType from 8a7f8ff88e79aca165c1f88cc6770c3447630a03 was NULL
Non-system Ruby in use. This may cause packaging to fail.
If you use RVM, please run `rvm use system`.
If you use chruby, please run `chruby system`.

2018-09-18 17:51:29.005 xcodebuild[60669:1389142] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/rn/110mft9515v2q5bgzk4jwgjc0000gn/T/zmNinja_2018-09-18_17-51-28.998.xcdistributionlogs'.
Exported zmNinja to: /Users/pp/projects/phonegap/zmNinja/platforms/ios/build/device
** EXPORT SUCCEEDED **

**Comment by neofuture** [comment] 2018-09-18 22:08
I use Cordova to create the project, but then I roll over to Xcode to increase versions, and upload to App Store via the organiser, I can build to emulator with the CLI but this is not ideal because version and build is reset to 1.0.0 each time and I maintain this in Xcode, I have since gone back to Xcode 9.4.1 with the exact same project and it builds from within Xcode and I can distribute (have the binary waiting for review now) 

if I distribute with Xcode 9.4.1 it does not complain about the missing provisioning, if I distribute with Xcode does, but this could be down to changes in the project files and that file being missing for the new style of build

**Comment by neofuture** [comment] 2018-09-18 22:09
"is there a problem wherein Cordova CLI is making builds with missing embedded mobileprovision files"

I can't confirm as the version numbers are all wrong in the build so I can't use application loader to push it up, but could it be the default required embedded mobileprovision should be in the Cordova iOS platform project and Xcode, not finding it, doesn't include it ?

**Comment by kitolog** [comment] 2018-09-19 07:30
Huh
I did it, so, for Ionic developers (and plain Cordova too) to solve problems with AppStore and Fabric
1) To build in console
`ionic cordova build ios -- --buildFlag="-UseModernBuildSystem=0"`
2) To run in console
`ionic cordova run ios -- --buildFlag="-UseModernBuildSystem=0"` 
3) To build archive using Xcode:
 - setup provisioning profile, certificates, etc. That's no matter using automatic or manual signing, do it habitual way as previously
 - In the Xcode, open Workspace Settings -> Build System -> and select Legacy Build System

Using Legacy Build System you will be able to build archive with normal mobileprovision and Info.plist files

<img width="349" alt="2018-09-19 9 08 46" src="https://user-images.githubusercontent.com/781366/45737593-f7e30780-bbf6-11e8-86f8-207dd596ad36.png">
<img width="538" alt="2018-09-19 9 09 03" src="https://user-images.githubusercontent.com/781366/45737603-fc0f2500-bbf6-11e8-84c9-8dcb17e7c691.png">

**Comment by phillipplum** [comment] 2018-09-19 08:35
Thank you @kitolog. This works for us!

**Comment by neofuture** [comment] 2018-09-19 08:51
Thanks @kitolog Legacy appears to be working for me, im just waiting for the binary to process

**Comment by Stefano1964** [comment] 2018-09-19 09:12
I always manually sign my apps, i never use command line, so i use Xcode, for me it's working also with the new build system in Xcode, i tried with an Ad Hoc export.

**Comment by neofuture** [comment] 2018-09-19 09:14
@Stefano1964 i can use the new build system in Xcode the issue is when trying to distribute, ad hoc will work but app store connect wont accept the binary because of a missing provisioning profile.

**Comment by rossholdway** [comment] 2018-09-19 10:15
@kitolog Thats for the workaround. Works for me 👍 (using the legacy build system now allows me to archive via Xcode 10 and the app validates successfully).

I think the issue here is that for some reason, the new build system doesn't include the `embedded.mobileprovision` within the app bundle for Cordova generated Xcode projects if you use automatic signing. I have a very basic native swift project that works fine with auto signing and the new build system.

![screen shot 2018-09-19 at 11 04 18](https://user-images.githubusercontent.com/2728159/45747223-0b916c80-bbfd-11e8-9ffc-91847cc61a26.png)

**Comment by peterpeterparker** [comment] 2018-09-19 11:12
I join @Stefano1964 on that one, I do the same, I process the signing of the app in Xcode and therefore it seems I don't face problems with my existing app/platform and Xcode 10

First I have added an `alert("test");` to my very first page, in order to be sure, when I would test, that I would see something different ;)

Then I opened Xcode 10 and selected "Generic iOS Device" (not sure it's relevant). Then Xcode began to index files. Under warnings I just found one warning asking me some modifications in the project regarding the signing, sorry went to fast, I'm dumb, any how I say yes ;)

Then I have build my app like I always do

     ionic cordova build ios --prod

Went back to Xcode 10, selected "iPhone 8" and launched ("Play button") my app which was launched without problems and my above alert was throw (once the app loaded of course)

That would also explain why I didn't noticed problems when I tested Xcode 10 beta back in June this year

**Comment by Stefano1964** [comment] 2018-09-19 12:52
To summarize, i think that actually the bug is related to the Cordova CLI.
For some reasons (path related?) the build with CLI fails with new build system not including the provisioning profile.

**Comment by Stefano1964** [comment] 2018-09-19 14:29
The new build system it's not failing in Xcode.

**Comment by Stefano1964** [comment] 2018-09-19 14:41
With command line it's failing because the provisioning profile it's not included in the build not because of the new build system, otherwise this wont work in Xcode too.

**Comment by dpogue** [comment] 2018-09-19 15:07
This is where I'm getting a bunch of contradictory information in these comments. Several people have said that the Cordova CLI is able to make successful builds with the provisioning profile included when using the `-UseModernBuildSystem=0` flag. Others have now said that it also works in Xcode after changing the build system preference in the Xcode UI.

So is this an accurate summary of what people are seeing?
* With Legacy Build System
  * With Cordova CLI (`-UseModernBuildSystem=0`)
    * Automatic Signing: **Works**
    * Manual Signing: **Works**
  * With Xcode (Workspace Settings -> Legacy Build System)
    * Automatic Signing: **Works**
    * Manual Signing: **Works**
* With Modern/New Build System
  * With Cordova CLI
    * Automatic Signing: **Fails?**
    * Manual Signing: **Maybe fails?**
  * With Xcode
    * Automatic Signing: **Fails**
    * Manual Signing: **Works?**

I need to understand what works and what's broken before I can start investigating how to fix it, and everyone's comments seem to be saying different things.

**Comment by Stefano1964** [comment] 2018-09-19 15:45
I suspect this has to do with automatic signing in all case where it fails. It's not a new issue with Xcode...

**Comment by rossholdway** [comment] 2018-09-19 15:54
Could be related? https://github.com/phonegap/phonegap-plugin-push/issues/2518

**Comment by dpogue** [comment] 2018-09-19 17:50
> Could be related? [phonegap/phonegap-plugin-push#2518](https://github.com/phonegap/phonegap-plugin-push/issues/2518)

I'm pretty sure that's unrelated. The embedded.mobileprovision is added (in this case) during the export step.

**Comment by newuser44** [comment] 2018-09-19 18:34
I can't tell where my problem is at.  I build the code using the command line.  That seems to work.  I open the project in Xcode and try to push to the phone.   It fails building for some signing reason.
All I see is 
Command /usr/bin/codesign failed with exit code 1

I'm not really sure what to even debug.  
I did setup in Xcode to use the new build process.  
I don't know if this is related or something else is wrong.

**Comment by dpogue** [comment] 2018-09-19 21:03
I think we've figured out the circumstances that cause this bug, and I've updated the Xcode 10 workaround announcement to avoid it.

In order to build Cordova apps on the command-line with Xcode 10, you need to set the `-UseModernBuildSystem=0` flag. However, this flag only applies for **that build**.

If you open the resulting project in Xcode, it will by default try to use the new build system. You **must update the workspace settings** in the Xcode IDE and set the Build System to Legacy before making any builds through the Xcode IDE.
See [this comment](https://github.com/apache/cordova-ios/issues/412#issuecomment-422689481) from @kitolog with helpful screenshots about how to do that.

As mentioned, I've updated https://github.com/apache/cordova-ios/issues/407 to include workaround instructions for anyone using the Xcode IDE, and I'm going to close this issue to try to keep all the information in one easily visible place. Thanks for your reports and error logs and patience everyone!

**Closed by dpogue** 2018-09-19 21:03 UTC
Labels: bug, discussion

**Comment by emirbosques** [comment] 2018-09-24 23:01
> Huh
> I did it, so, for Ionic developers (and plain Cordova too) to solve problems with AppStore and Fabric
> 
> 1. To build in console
>    `ionic cordova build ios -- --buildFlag="-UseModernBuildSystem=0"`
> 2. To run in console
>    `ionic cordova run ios -- --buildFlag="-UseModernBuildSystem=0"`
> 3. To build archive using Xcode:
> 
> * setup provisioning profile, certificates, etc. That's no matter using automatic or manual signing, do it habitual way as previously
> * In the Xcode, open Workspace Settings -> Build System -> and select Legacy Build System
> 
> Using Legacy Build System you will be able to build archive with normal mobileprovision and Info.plist files
> 
> <img alt="2018-09-19 9 08 46" width="349" src="https://user-images.githubusercontent.com/781366/45737593-f7e30780-bbf6-11e8-86f8-207dd596ad36.png">
> 
> <img alt="2018-09-19 9 09 03" width="538" src="https://user-images.githubusercontent.com/781366/45737603-fc0f2500-bbf6-11e8-84c9-8dcb17e7c691.png">

Excellent!! Work for me! 
Thanks! @kitolog

**Comment by ajayprakashshukla** [comment] 2018-09-25 13:37
Using Legacy Build System you will be able to build archive with normal mobileprovision and Info.plist files

**Comment by pliablepixels** [comment] 2018-09-26 19:54
I'm not sure you are facing the same error as I did - in your case it seems `--buildFlag` is not recognized. I use cordova 8, cordova-ios 4.5.5


I shiver when I am asked to relive nightmares. Now that this is solved, I'm battling with WKWebView and self signed certs and the fact that Android builds have issues (when WKWebView is an iOS thing). Jokes apart -  back to your question: 

Here is what I do now:

1. To build from CLI, I use 
`ionic cordova build ios --release --buildConfig="./build-auto.json"`
([my build-auto.json](https://github.com/pliablepixels/zmNinja/blob/master/build-auto.json))

2. When I build using Xcode, I make sure "Legacy build system" is on as per the posts above.

Hope this helps.

**Comment by collindutter** [comment] 2018-09-26 20:06
Well I truly don't know what I did, but after enough head banging, it works now? I think my ng-toolkit might've been out of date. For anyone in my exact scenario, here's my info and what I'm running to get it working.

```

Ionic:

   ionic (Ionic CLI)          : 4.1.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.11
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.1.4, (and 6 other plugins)

System:

   ios-deploy : 2.0.0
   NodeJS     : v10.11.0 (/usr/local/Cellar/node/10.11.0/bin/node)
   npm        : 6.4.1
   OS         : macOS
   Xcode      : Xcode 10.0 Build version 10A255
```
`ionic cordova run ios --verbose -- -- --buildFlag="-UseModernBuildSystem=0"`
(notice the two --)

Also, thanks @pliablepixels, good luck with your current issues.

**Comment by joelsonrocha** [comment] 2018-10-02 14:49
Hi,

Access https://developer.apple.com/account

1 - Certificates, IDs & Profiles

2 - Provisioning Profiles

3 - Distribution

4 - Add Button 

5 - Distribution -> App Store -> Continue

6 - Choose Apple Id -> Continue

7 - Select certificates -> Continue

8 - Set Profile Name -> Continue

9 - Download

10 - In Xcode -> Product -> Archive, In Re-sign "App Name" make option Manually manage signing -> choose the Distribution certificate and import your provisioning profile downloaded on step 9.



Sorry for my English, I'm from Brazil

**Comment by csotomon** [comment] 2018-10-03 03:48
@joelsonrocha 's solution works for me

**Comment by godexsoft** [comment] 2019-01-28 12:01
It can be made to work with all the hacks above. The real question is why is there debug and release sections in the json.build but only either one makes it to BOTH debug/release sections in the xcode project depending on the --debug/--release switch in cordova CLI. it does not make too much sense. A much better way would be to populate xcode project with both debug and release profiles and then just compile/build the correct version depending on the cli switch.

Is there anything i'm missing? maybe i did not understand how to use it correctly?

**Comment by clusterr023** [comment] 2019-02-27 18:03
I have the same problem where automatic signing + new build system does not include the embedded.provisionprofile.

With the legacy build it works but then i have a few plugins that refuse to work. They do work when i build using the new build system but then it fails when trying to upload to apple.

Any solutions? How do i force xcode to create the embedded.provisionprofile using the new build system and automatic signing.

**Comment by dpogue** [comment] 2019-02-27 18:04
@clusterr023 This should be fixed in cordova-ios@5.0.0

**Comment by markterrill** [comment] 2019-06-10 06:05
Hi,
An important thing that helped me with notifications: Edit your Xcode scheme to use Release as its deployment type.

Product > Scheme > Edit scheme > Run (on the left panel) > Info tab > 'Build Configuration' set to 'Release'. Close and then play/run again to your phone.

**Comment by HarelM** [comment] 2019-12-28 20:55
I might be missing out something very simple but reading the docs and this thread and trying out things did not work for me.
What I would like to do is create an ipa purely from command line without opening xcode at all and without macos popups.
I want to create an app using appveyor build system which now support macos image.
I couldn't understand from the docs and from the thread here how I can achieve this.
If anyone has a working example or some details on how to do it, it would help a lot.
I can open a different issue for this if needed.
I have a developer account. I'm able to manually publish packages but I don't understand how to make the build system create a package I can later upload to app store connect/manually sign it or what not. Any help/link/instructions would be helpful.

**Comment by breautek** [comment] 2019-12-28 21:11
@HarelM This issue is for distributing an app using Xcode.

I'm not familiar with appveyor but Apple essentially gives you two ways to distribute to iTunes Connect/App Store.

1) Via Xcode GUI directly

2) Use XCode to build a signed IPA file, then use Apple's [Transporter](https://apps.apple.com/app/transporter/id1450874784?mt=12) app to upload the IPA file.

If you have anymore questions I encourage you to join [slack](http://slack.cordova.io/) and ask support style questions there.
