### ISSUE TITLE
XCode cannot build : Cordova.h and Info.plist missing files 

### ISSUE THREAD

**Issue by mushu8** [apache/cordova-ios#760] opened 2020-01-03 13:56 UTC
# Bug Report

## Problem
I cannot build my XCode project generated by Cordova :

CordovaLib.xcodeproj/Cordova/Cordova.h and CordovaLib.xcodeproj/Cordova/Info.plist files are not generated thus an error is thrown during XCode compilation.

### What is expected to happen?
I can build and run my project.

## Information

I tried to get these files from the cordova-ios repository and add them (and link) manually in the XCode project but others errors are thrown by the compiler

### Command or Code
these commands don't show any errors and very few warning (ld file or directory not found for -F… due to the cordova-plugin-firebasex plugin) :
* ionic cordova platofrm add ios --no-resources
* ionic cordova build ios --debug --buildConfig=./resources/ios/build.json --source-map

### Environment, Platform, Device
Mac OS X Mojave 10.14.5 (18F132)
iOS 12.0

### Version information
Ionic:
   Ionic CLI                     : 5.4.13 (~/.nvm/versions/node/v10.14.1/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.7
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                                : 8.1.3
   @ionic/angular-toolkit                : 2.0.0

Cordova:
   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 9 other plugins)

Utility:
   cordova-res                          : 0.8.1
   native-run                             : 0.3.0

System:
   Android SDK Tools : 26.1.1 (~/Library/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v10.14.1 (~/.nvm/versions/node/v10.14.1/bin/node)
   npm               : 6.13.1
   OS                : macOS Mojave
   Xcode             : Xcode 11.2.1 Build version 11B500

## Checklist
- [X] I searched for existing GitHub issues
- [X] I updated all Cordova tooling to most recent version
- [X] I included all the necessary information above

**Comment by brodybits** [comment] 2020-02-18 19:51
I just added the **help wanted** label. It would be extremely helpful for us if you could give us the [minimal, reproducible example ([1])](https://stackoverflow.com/help/minimal-reproducible-example) with no use of Ionic. Also this looks like a custom build procedure which we do not have the extra resources to support.

How to embed in an existing application was already documented. I am not sure if anyone has tested this in the past few years.

[1] https://stackoverflow.com/help/minimal-reproducible-example

**Comment by fwgood** [comment] 2020-05-12 03:01
I have the same error
![image](https://user-images.githubusercontent.com/16516811/81633728-fc011000-943f-11ea-8a30-85b5a23f41a6.png)

**Comment by feniquill** [comment] 2020-05-15 23:18
I am also getting the same error trying to build from the xcode app 
![Screen Shot 2020-05-15 at 5 18 22 PM](https://user-images.githubusercontent.com/8510231/82103415-236e0c00-96d0-11ea-8f4e-de7a68654f18.png)

**Comment by lucianotrevisanalberti** [comment] 2020-06-17 20:23
I get the same error.

![Captura de Tela 2020-06-17 às 17 05 02](https://user-images.githubusercontent.com/20960016/84946487-31dc8880-b0bf-11ea-8d94-d1ec2d5629fa.png)

**Comment by brodybits** [comment] 2020-06-17 20:47
@lucianotrevisanalberti it looks like your Xcode GUI is trying to just build the Cordova subproject, which is not really tested or supported by us. Please click on this control and use it to select your application build project:

<img width="224" alt="Screen Shot 2020-06-17 at 4 44 20 PM" src="https://user-images.githubusercontent.com/1559888/84948612-fa1f1200-b0b9-11ea-8ea2-82e001a43984.png">

I suspect that this would affect other users. I think this should be documented as a pitfall.

**Comment by lucianotrevisanalberti** [comment] 2020-06-17 20:55
guys, the problem was fixed deleting "ios" folder (inside of "platform" folder) and running "build" again... Build Success

**Comment by Rahulbhutani97** [comment] 2020-12-27 17:31
same issue i faced now, already did above mentioned things. Not working that, any solutions ? @brodybits @lucianotrevisanalberti @feniquill @mushu8

**Comment by brodybits** [comment] 2020-12-28 14:52
@Rahulbhutani97 it looks like there is something wrong with your project or installation. I would highly recommend you check that you have all tools updated and start with a new workarea, no `plugins` or `platforms` folders. For further support please give us the information requested in the template. Thanks.

I have raised https://github.com/apache/cordova-docs/issues/1143 to get the pitfall documented.

**Comment by Rahulbhutani97** [comment] 2020-12-28 17:31
@brodybits thanks i update my screenshot there for reference at [https://github.com/apache/cordova-docs/issues/1143](https://github.com/apache/cordova-docs/issues/1143)

**Comment by brodybits** [comment] 2020-12-28 18:05
> <img alt="Screenshot 2020-12-28 at 10 54 08 PM" width="1130" src="https://user-images.githubusercontent.com/39648519/103232258-04bb3d80-4960-11eb-96c4-4cf207453cf7.png">
> 
> Build succeded :: in VScode
> 
> <img alt="Screenshot 2020-12-28 at 10 56 03 PM" width="836" src="https://user-images.githubusercontent.com/39648519/103232263-07b62e00-4960-11eb-8716-b1e34a252cb3.png">
> 
> When i open .xcodeProj file then run build it shows error of info.plist

The screenshot should have been here, <https://github.com/apache/cordova-docs/issues/1143> is just to get the pitfall documented for others.

I personally find it easiest to just open the project in platforms/ios in Xcode and build from there.

**Comment by Rahulbhutani97** [comment] 2020-12-28 18:36
What I mistaken?? 
.xcodeproj open in xcode or just open platform/ios folder in xcode?

**Comment by brodybits** [comment] 2021-01-03 00:09
You should open the .xcodeproj in Xcode (it is in platofrms/ios) then build and run.

**Comment by Rahulbhutani97** [comment] 2021-01-03 03:20
Already did

**Comment by Rahulbhutani97** [comment] 2021-01-04 17:27
Issue reolved... yeah :)

**Comment by andresloopear** [comment] 2021-01-11 18:12
@Rahulbhutani97 how did you solved it?

**Comment by Rahulbhutani97** [comment] 2021-01-11 18:19
signin with your team (i.e. apple account) 
then in xcode under Product > Archive 
then you will get Build succeeded or failed 
https://blog.rahulbhutani.com/ connect me here if you want

**Comment by radu2323** [comment] 2021-05-12 07:18
I managed to fix this by selecting my application build project. It seems that by default, the Cordova subproject is selected in Xcode GUI.

Found this thanks to this post from above [https://github.com/apache/cordova-ios/issues/760#issuecomment-645616290](url).

I think this is the correct answer for this issue.

**Comment by rmeske** [comment] 2021-07-20 15:25
I just ran into this today with an existing Ionic project that worked fine.  I am on Big Sur (11.4) and running Xcode 12.5.1, Ionic 6.13.1 and Cordova 10.0.0.

I have removed the iOS platform and the added again.  I get a successful build with Ionic/Cordova, but when I open in Xcode and try to build the project it is giving a build error and indicates the Cordova folder, Info.plist & Cordova.h are missing from CordovaLib.xcodeproj. 

I have tried set the device to "Any iOS Device" as well as specific platforms, all with the same result.  The error seems to be more related to the Cordova build process.

Any suggestions?

**Comment by Rahulbhutani97** [comment] 2021-07-20 16:01
Hy

Add info.plist file and cordova.h

And check info.plist was there ??? Actually it is default to be there

**Comment by rmeske** [comment] 2021-07-20 23:17
I reopened the project to add the files and and noticed it was giving a conflict on the signing.  So first, I unchecked the "Automatically manage signing" and then rechecked it and added the Team back.  It now builds successfully.

The two files are missing but Xcode successfully builds and the app runs properly.

**Comment by Rahulbhutani97** [comment] 2021-07-21 01:32
Greatt

If any work you have for me like any paid task i am available to you

Shall we connect further ??

**Comment by andres199556** [comment] 2021-09-30 15:35
No se si aya se encontró la solución, en mi caso era porque estaba abriendo el archivo de .xcodeproj, lo cual no cargaba correctamente el proyecto, opte por cargar el archivo .xcworkspace y cargó a la perfección.

**Comment by chr15m** [comment] 2023-01-13 02:47
I intermittently get this error in the form of missing Info.plist in the CordovaLib scheme. Selecting the app scheme in XCode does not seem to fix the error. Sometimes the file is generated when running prepare and build, and sometimes it isn't.

**Comment by fwgood** [comment] 2023-01-13 02:47
已收到您的邮件，会尽快回复

**Comment by dpogue** [comment] 2023-01-13 02:48
I believe this can happen if you open the project's `.xcodeproj` file rather than the project's `.xcworkspace` file.

**Comment by chr15m** [comment] 2023-01-13 02:53
@dpogue thank you that seems to have fixed the issue so far. Will post here if it happens again.

**Comment by Mady-Camara** [comment] 2023-01-18 07:22
@dpogue it works perfectly 👍🏾

**Comment by dpogue** [comment] 2023-04-16 01:10
It seems like opening the project's .xcworkspace works, so I'm going to close this issue.

**Closed by dpogue** 2023-04-16 01:10 UTC
Labels: support
