### ISSUE TITLE
Cordova iOS ignores config-file in plugin.xml

### ISSUE THREAD

**Issue by Durzan666** [apache/cordova-ios#581] opened 2019-03-26 14:02 UTC
# Bug Report

## Problem
In one of my plugins I define in the plugin.xml a custom URL scheme like this
```
<config-file target="*-Info.plist" parent="CFBundleURLTypes">
      <array>
        <dict>
          <key>CFBundleURLSchemes</key>
          <array>
            <string>foobar</string>
          </array>
          <key>CFBundleURLName</key>
          <string>com.my.Foobar</string>
        </dict>
      </array>
    </config-file>
```
but it doesn't appear in my <Project name>-Info.plist
### What is expected to happen?
The changes made by a plugin.xml targeting the Info.plist are available as usual.

### What does actually happen?
Cordova ignores the changes to Info.plist which can be found in a plugin.xml

## Information

This problems doesn't appear with cordova@8.1.1 and cordova-ios@4.5.5 
but with cordova@9.0.0 and cordova-ios@5.0.0

### Command or Code

cordova platform add ios@5.0.0

### Version information

MacBook Air (mid 2012) with Mojave (10.14.3) 
Xcode 10.1

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by dpogue** [comment] 2019-04-17 04:23
This might be a duplicate of #401.

**Comment by l3ender** [comment] 2019-07-30 00:59
We're seeing this same issue. Is there any workaround?

**Comment by Durzan666** [comment] 2019-08-05 05:56
@l3ender Yes. We added the iOS platform with the previous cordova-ios release and saved the plist file. Then we wrote a hook to copy the previous saved plist file after platform add.

**Closed** 2019-08-21 03:23 UTC
