### ISSUE TITLE
ionic1 run in ios( my iphone6 ), all cordova plugin can't not be use

### ISSUE THREAD

**Issue by NetZAL** [apache/cordova-ios#626] opened 2019-06-04 02:39 UTC
$ionicPlatform.ready() { console.log('hello'); } , the function never be call, and I never see the 'hello', and all the cordova plugins can not use。
when I build android apk, It's work, but when I build in IOS( my iphone6 ), is not work.
I want to know why my device can't not be ready. I can't use any plugins, like camera 、media.

**Comment by janpio** [comment] 2019-06-04 09:08
> $ionicPlatform.ready() { console.log('hello'); } , the function never be call, and I never see the 'hello',

This sounds like an Ionic problem then. Probably `$ionicPlatform.ready()` is somehow broken or doesn't do its job as it should.

Can you reproduce the problem in a new Ionic app?

**Comment by NetZAL** [comment] 2019-06-04 10:03
Thank you!  Now I don't have the time to reproduce this problem.  But I finded the problem now, it's not the ionic problem, it's ios version problem.  I reduce the ios version when I run the command( cordova platform add ios ), I have find so long, I can't understant, why the higher version can't work, high version should compatible the lower one, right ? 

Haha, My english not good, I have try my best to express my solution.  I don't know weather you understand what I said.

Thanks again.

**Comment by janpio** [comment] 2019-06-04 10:22
Your English is pretty good - totally clear what you are saying.

What iOS version are you having problems with?
What Cordova iOS version were you trying before and what did you switch to?

**Comment by NetZAL** [comment] 2019-06-04 10:29
Now I ready go off work, I close my VMware Workstation, I will tell you tomorrow

**Comment by NetZAL** [comment] 2019-06-05 01:43
I think is not my phone problem, it's cordova ios version problem.
When I run cordova paltform add ios, the acquiesce in the ios version is 4.2.1, and I switch to the 4.1.0. It's ok.
Now, I have finded the new problem, when I use cordova-plugin-camera to take a photo, the app is dead, Haha, why so many problem, do you have any solutions?

**Comment by janpio** [comment] 2019-06-05 07:30
Current cordova-ios version is 5.0.1 - and that works with all supported iOS versions.

**Comment by jcesarmobile** [comment] 2019-06-11 11:56
Closing as I can't reproduce on 5.0.1 and the issue is related to older versions.

**Closed by jcesarmobile** 2019-06-11 11:56 UTC

**Comment by NetZAL** [comment] 2019-06-12 02:19
Hi,  I have a question. Why my ios can't record, I useing the cordova-plugin-media, when I startRecord, It get error  immediately. run the error callback.  But run in android is OK. ---
Do you have some record plugin which can run in android perfect ? and if the plugin can return the base64 is better.
