### ISSUE TITLE
Issue with corodva and iOS14

### ISSUE THREAD

**Issue by srinivaschaval** [apache/cordova-ios#961] opened 2020-07-30 01:16 UTC
Hi Team, Our project is using Cordova 5.1.1 with wkwebview plugin and runs fine on all versions of iOS till iOS13. with recent testing we are doing on iOS14 Beta, the app is not able to load the index.html from the www folder and is showing a blank page on launch. Upon futher reserach issue is with the app name. Our app name has a special charater and since cordova appends app name to local file path when accessing index.html, the special character/symbol in app name is causing the issue. Everything works normal when remiving the special charater/symbol. This looks like a bug that is  coming with iOS14. Could you please suggest?

**Comment by dpogue** [comment] 2020-07-30 01:19
This sounds like a bug with iOS 14 beta. Please file a Radar bug report Apple: https://feedbackassistant.apple.com/

**Comment by breautek** [comment] 2020-07-30 01:19
Duplicate of https://github.com/apache/cordova-ios/issues/954

If you have any new information on this issue, please do share on #954

**Closed** 2020-07-30 01:19 UTC
