### ISSUE TITLE
Cordova overwrites bundleIdentifier for watchOS and error in Cordova build.

### ISSUE THREAD

**Issue by ksp143** [apache/cordova-ios#877] opened 2020-05-29 18:48 UTC
# Bug Report

### What does actually happen?
When Cordova projects contains watch targets (watchkit, watch extension) which have their own bundle id setup, Cordova overwrites all targets with the same id.

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by dpogue** [comment] 2020-05-29 18:51
Duplicate of https://github.com/apache/cordova-ios/issues/538. This should be addressed in the upcoming Cordova-iOS 6.0 release.

**Closed by dpogue** 2020-05-29 18:51 UTC
