### ISSUE TITLE
Inconsistent view movement when keyboard is shown

### ISSUE THREAD

**Issue by Steve-Frizzell** [apache/cordova-ios#777] opened 2020-01-31 20:17 UTC
# Bug Report
Inconsistent view movement when keyboard is displayed

## Problem
After dismissing a modal view controller, views shift up too far or not all when focusing a text field prompting keyboard display.

### What is expected to happen?
When focusing a text field for entry, I expect the view to shift up slightly to make sure the text field is visible and not covered by the keyboard.

![IMG_0009](https://user-images.githubusercontent.com/60517426/73571157-98744900-4433-11ea-815e-49c49ee0c825.png)

### What does actually happen?
The expected behavior happens _until a modal view controller is presented and dismissed_. From that point on, all views will shift up too far or not at all when a textfield is focused.

![IMG_0010](https://user-images.githubusercontent.com/60517426/73571174-a1651a80-4433-11ea-9fc4-a47375564d90.png)

## Information
 My application was created using ionic V1. I recently upgraded to Cordova-ios 5.1.1 to address Apple's upcoming App Store requirement for WkWebView. I also installed three cordova-plugin-wkwebview-* plugins as noted in the version information below. I tried replacing ionic-plugin-keyboard with Cordova-plugin-keyboard, but the results are the same. I also tried cordova-plugin-ionic-keyboard. I even tried replacing Cordova-plugin-wkwebview-* plugins with Ionic versions.

### Environment, Platform, Device

Multiple versions of iPhone

### Version information

iOS 12.4.1, iOS 13+
 
Xcode 11.3

Installed platforms:
  cordova-ios 5.1.1

cordova-plugin-app-event 1.2.2 "Application Events"
cordova-plugin-appxmanifest 1.0.0 "Windows Add privateNetworkClientServer Capability"
cordova-plugin-badge 0.7.2 "Badges"
cordova-plugin-camera 2.1.0 "Camera"
cordova-plugin-check-image 1.0.0 "MiSnapPlugin"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 1.1.1 "Device"
cordova-plugin-dialogs 1.2.1 "Notification"
cordova-plugin-drawshape 1.0.0 "DrawShapePlugin"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.5.1 "File Transfer"
cordova-plugin-geolocation 2.4.2 "Geolocation"
cordova-plugin-secure-app 1.0.0 "SecureApp"
cordova-plugin-whitelist 1.2.1 "Whitelist"
cordova-plugin-wkwebview-engine 1.2.1 "Cordova WKWebView Engine"
cordova-plugin-wkwebview-file-xhr 2.1.1 "Cordova WKWebView File XHR Plugin"
cordova-plugin-wkwebviewxhrfix 0.1.0 "WKWebView XHR Fix"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
ionic-plugin-keyboard 2.2.1 "Keyboard"

ionic v1

## Checklist

- [x] I searched for existing GitHub issues 
- [ ] I updated all Cordova tooling to most recent version 
- [x] I included all the necessary information above

**Comment by dpogue** [comment] 2020-01-31 20:20
Duplicate of #417

**Closed by dpogue** 2020-01-31 20:20 UTC
