### ISSUE TITLE
IOS_DIR not defined

### ISSUE THREAD

**Issue by ThatAbstractWolf** [apache/cordova-ios#610] opened 2019-05-03 08:52 UTC
# Bug Report

## Problem

I just updated to the latest version of Cordova IOS, I run "cordova build ios" and I get 1 response "IOS_DIR is not defined". 

### What is expected to happen?

Cordova should build the IOS project.

### What does actually happen?

I get the error suggested above.

## Information

<img width="545" alt="Screenshot 2019-05-03 at 09 51 03" src="https://user-images.githubusercontent.com/19803119/57127668-0f878e80-6d89-11e9-80ce-1bc9244ce3dc.png">

### Command or Code

`cordova build ios
`
### Environment, Platform, Device

Macbook Pro 2017 with Touchbar on latest version of IOS.

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by janpio** [comment] 2019-05-03 09:44
`IOS_DIR` is not part of this codebase, so this is a bit strange.

Can you run `cordova build ios --verbose` please?

What is your `cordova platform list` output?
What is your `cordova plugin list` output?

Have you tried removing and re-adding the iOS platform to your project?

**Comment by ThatAbstractWolf** [comment] 2019-05-03 09:49
Ah, apologies @janpio. Seems to be a plugin I have installed is causing this known as Marketo.

<img width="1058" alt="Screenshot 2019-05-03 at 10 48 30" src="https://user-images.githubusercontent.com/19803119/57130327-05698e00-6d91-11e9-9284-7adc458697c2.png">

I will try my best to contact them, if you have no ideas?

**Comment by janpio** [comment] 2019-05-03 09:56
Never used that one, sorry.

I'm going to close this, as it is not caused by cordova-ios.

**Closed by janpio** 2019-05-03 09:56 UTC
