### ISSUE TITLE
WKWebview requires NSURLProtocol Interceptor for https URL

### ISSUE THREAD

**Issue by karthibv** [apache/cordova-ios#587] opened 2019-03-31 02:27 UTC
# Bug Report
Need default schema (https) intercept support in WKWebview.

## Problem
We are using UIWebview can intercept the request by registering NSURLProtocol, then we can load local files sources instead of download from remote, We would want to move WKWebview instead of UIWebview but which is not supporting NSURLProtocol.

### What is expected to happen?
We would want default schema support in WKWebview which can intercept https schema requset and the load the resources from local.

### What does actually happen?
 iOS 11 onwards Apple supporting WKURLSchemeHandler, which is also supporting custom schemes, if we try with default scheme (https), then getting exceptions. 

### Environment, Platform, Device
IOS 11 onwards

### Version information
iOS 11

**Comment by dpogue** [comment] 2019-03-31 02:32
This is a duplicate of the feature request at #415.

Note however, that even WKURLSchemeHandler cannot intercept HTTP or HTTPS request. It requires you to register your own custom scheme, which can be routed to local resources.

**Closed by dpogue** 2019-03-31 02:32 UTC
