### ISSUE TITLE
Cannot use custom scheme in embedded web view

### ISSUE THREAD

**Issue by alekop** [apache/cordova-ios#1163] opened 2021-10-19 20:43 UTC
Native SwiftUI app with embedded Cordova Web view. Loads fine using the file scheme, but I would like to use a custom scheme in order to establish a secure context. I've added the scheme and hostname preferences to config.xml file:

    <preference name="scheme" value="app" />
    <preference name="hostname" value="localhost" />

`CDVWebViewEngine.pluginInitialize` creates the scheme handler, and attaches it to the configuration:

    self.schemeHandler = [[CDVURLSchemeHandler alloc] initWithVC:vc];
    [configuration setURLSchemeHandler:self.schemeHandler forURLScheme:scheme];

Finally, `CDVWebViewEngine.loadRequest` calls WKWebView.loadRequest with "app://localhost/index.html"... But the `CDVURLSchemeHandler.startURLSchemeTask` method is never called, and the web view remains on about:blank. Tried setting location.href manually (via the Safari dev tools), but nothing loads.

The view controller is exposed to SwiftUI like so:

    class CordovaWebViewController: CDVViewController {
        init() {
            super.init(nibName: nil, bundle: nil)
        }
    
        required init?(coder: NSCoder) {
            super.init(coder: coder)
        }
    }

    struct CordovaWebView: UIViewControllerRepresentable {
        typealias UIViewControllerType = CordovaWebViewController
    
        func makeUIViewController(context: Context) -> CordovaWebViewController {
            CordovaWebViewController()
        }
    
        func updateUIViewController(_ uiViewController: CordovaWebViewController, context: Context) {
        }
    }

And used like this:

```
struct ContentView: View {
    var body: some View {
        CordovaWebView()
    }
}

```

Is there anything extra I need to do for an embedded view?

**Comment by msmtamburro** [comment] 2023-06-26 20:56
I saw this issue with schemes, which had the same behavior: https://github.com/apache/cordova-ios/issues/1223#issuecomment-1608211672

**Comment by breautek** [comment] 2023-10-21 11:12
Closing this as a duplicate of https://github.com/apache/cordova-ios/issues/1163

Favouring https://github.com/apache/cordova-ios/issues/1163 because it seems more progressed and it's a more recent reported ticket.

**Closed by breautek** 2023-10-21 11:12 UTC
