### ISSUE TITLE
Rename generated Xcode project to "CordovaApp" or something consistent

### ISSUE THREAD

**Issue by dpogue** [apache/cordova-ios#1464] opened 2024-08-16 20:53 UTC
# Feature Request

## Motivation Behind Feature

Currently, the generated Xcode project uses the application name for both the project and the target name. This means that file paths in generated projects are not consistent and we have to do regex-based token replacements during project creation. It also makes modifying the template project a pain because opening the template project directly in Xcode causes a bunch of those tokens to break.

The deeper problem is that some tooling (notably Cocoapods) struggles with project and target names with non-ASCII characters. By making the project name consistent, we can hopefully avoid those problems.

This could potentially also solve long-standing issues around `<config-file>` and `<edit-config>` for things like the Info.plist (currently named `{{projectname}}-Info.plist`) and node-xcode corrupting other targets due to not being able to restrict changes to just the app target.

## Feature Description

The generated Xcode project would be named `App.xcodeproj` or `CordovaApp.xcodeproj`.
The application target within that project would be named `App` or `CordovaApp`.

**Prior Art:** Capacitor projects are named `App.xcodeproj` with a default target named `App`.

## Alternatives or Workarounds

The current method mostly works (as long as you don't have non-ASCII characters in the project name), so there's a valid argument for keeping the existing behaviour.

The workaround for now is to generate a project with an ASCII name and then override the app's display name, which is pretty much what this change would accomplish by default.

Ref https://github.com/apache/cordova-ios/issues/717.
Ref https://github.com/apache/cordova-ios/issues/1150.
Ref https://github.com/apache/cordova-ios/issues/1289.

**Comment by erisu** [comment] 2024-08-23 05:46
I think having a consistent project name is a great idea.

Beyond the issues caused by non-ASCII project names, I've also heard of cases where hook scripts were needed to modify something within the project workspace. However, because the project name was inconsistent, they had to parse directory paths to extract the project name. A consistent project name would simplify this process.

It would also help clean up some of the node side in Cordova-iOS.

**Comment by erisu** [comment] 2024-09-03 18:31
@Mrkvozrout you might want to take a look at PR #1485

The above PR is refactoring to make the name of the app template/Xcode project consistent and will be hard set to `App`. E.g. `App` dir, `App.xcworkspace`, & `App.xcodeproj` etc...

The `name` element will remain the same `<name short="Short App Name">Long Name of My App</name>` but wont be used for defining any project file or directory names.

**Comment by Mrkvozrout** [comment] 2024-09-04 07:31
I saw it and understood but thought that custom project name might be useful and offered solution.

Anyway the fixed project name is simpler and sufficient (and I guess it is consistent with the android's `app` gradle subproject).

So good for me and lets hope your PR is merged and delivered soon :)

**Comment by Mrkvozrout** [comment] 2024-09-04 14:02
Question about the PR - Will "dynamic" change of name (`<name>` element value in `config.xml`) work as expected?

Expectation - if I update the name via hook early enough (`before_prepare` or `before_platform_add`), the new name should be used as the application name (on all needed places in the project in order to be visible after installation to device).

I tried to change the name in `before_platform_add` hook, which feels to be early enough for ios platform to not perceive it as a dynamic change, but I still get this error:
`The product name change (<name> tag) in config.xml is not supported dynamically.`

To be answered:
- Will app name change work with this PR?
- Is next release the 8.0.0? (if yes, what it the expected rough release date?)
- Will there be some intermediate 7.x release? (if yes, I would create an issue to allow app name change in `before_platform_add` hook)

Thanks for answers in advance

**Comment by breautek** [comment] 2024-09-04 14:16
> Question about the PR - Will "dynamic" change of name (<name> element value in config.xml) work as expected?

That check will be removed allowing name changes across builds (without removing and re-adding the platform) via 
https://github.com/apache/cordova-ios/pull/1485/files#diff-3f506429799383a7a5415e9eef05bc14959c37346194ecd50394ea404b64487aL265

> Is next release the 8.0.0? (if yes, what it the expected rough release date?)

It is being treated as a breaking change, among several other improvements so it will be part of a 8.0.0 released, assuming #1485 does indeed gets merged. Due to the volunteer nature of Apache Cordova project we can't reliably give any timelines.

> Will there be some intermediate 7.x release? (if yes, I would create an issue to allow app name change in before_platform_add hook)

Unlikely because the [repo](https://github.com/apache/cordova-ios/blob/master/package.json#L3) is already in a `8.0.0-dev` state, meaning it likely has breaking changes already merged.

As a workaround for the time being...

In my workflows I have `config.xml` gitignored and is generated via tooling based on the environment I want to build for (e.g. different app ids & name for staging vs production). Switching environments does involve removing the platform, run a script to generate a config.xml for the specific enviroment and then re-add the platform. This works since the config.xml is updated before calling on any Cordova tooling. It's not most efficient workflow especially if you're requiring changing environments frequently but it works for current versions of Cordova.

**Closed** 2024-10-08 07:02 UTC
Labels: enhancement
