### ISSUE TITLE
App rejected by Apple: App does not clarify the use of Motion Sensor in the applicable purpose string

### ISSUE THREAD

**Issue by Dirk-27** [apache/cordova-ios#891] opened 2020-06-08 09:37 UTC
# Bug Report
App rejected by Apple: App does not clarify the use of Motion Sensor in the applicable purpose string.
This is because we need the Motion and Orientation data. To access them the webview asks for permission as shown in the screenshot below.

Also the user response is not noticed. Every time the app is deleted from the background, the app ask for permission again.

## Problem
Our ios app has been recently always rejected by Apple with the following message.

>5. 1.1 Legal: Privacy - Data Collection and Storage
>Guideline 5.1.1 - Legal - Privacy - Data Collection and Storage
>We noticed that your app requests the user’s consent to access their camera and Motion Sensor
>but does not clarify the use of the camera and Motion Sensor in the applicable purpose string.

### What is expected to happen?

![hh](https://user-images.githubusercontent.com/45331389/84011982-267ab600-a977-11ea-8a0f-56be0d574a39.png)

### What does actually happen?

![IMG_0007](https://user-images.githubusercontent.com/45331389/84010385-dc90d080-a974-11ea-80d5-0dc9eef44e4a.PNG)

We have found something similar and maybe it could be solved like [this](https://stackoverflow.com/a/59542677)

**Comment by mosabab** [comment] 2020-06-12 22:56
You need to clarify to users why you use the camera, this can be done by adding the reasons in this way, you can refer to this:
https://github.com/apache/cordova-plugin-camera#ios-quirks

**Comment by breautek** [comment] 2020-06-13 01:59
Duplicate of https://github.com/apache/cordova-plugin-device-motion/issues/69

**Closed by breautek** 2020-06-13 01:59 UTC
